version: '2'

services:
  unews-server:
    image: unews-server
    build:
      context: ./ZeusApps.News.Server
      dockerfile: Dockerfile
    depends_on:
      - mongo
  unews-parser:
    image: unews-parser
    build:
      context: ./ZeusApps.News.Parser
      dockerfile: Dockerfile
    depends_on:
      - unews-server
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: